MANAGER_TICKET_SECTION_MENU : |
  Press:
  'a': view all tickets
  'q': back
  Your choice: 

EMPTY_TICKETS : "No tickets to show"

ALL_TICKETS_WELCOME : "Here are the latest tickets raised by customers in our organization"

END_OF_TICKETS : "---------------------------That's all the tickets we have---------------------------"

ALL_TICKETS_PROMPT : |
  Press:
  'n': next page
  'q': back
  Your choice:

ALL_TICKETS_CONTINUE_PROMPTS : "Do you want to see all the tickets again?(y/n)"

DETAIL_T_ID_PROMPT : "Enter the ticket id of ticket you want to see in detail: "

INVALID_T_ID : "Enter valid ticket id or press q to go back: "

CLOSED : "closed"

GO_BACK_PROMPT : "Press q to go back: "