
WELCOME_HELPDESK_SECTION : "---------------------------Welcome to tickets section---------------------------"

UNRESOLVED_TICKETS_WELCOME : "Here, are the latest unresolved tickets: "

CLOSE_TICKET_WELCOME : "Here are the available tickets please enter the ticket id for which you want to delete: "

TICKET_IN_DETAIL_WELCOME : "Ticket: "

PLEASE_ENTER_VALID_INPUT : "Please enter a valid input: "

RESOLVED_TICKET_WELCOME : "Here are the resolved tickets: "

RESOLVE_TICKET_PROMPT : "Enter ticket id  of the ticket you want to resolve: "

CLOSED_TICKETS_WELCOME : "Here are the latest closed tickets: "

HELPDESK_TICKET_PROMPT : |
  Press:
  'u': unresolved tickets
  'r': resolved tickets
  'c': closed tickets
  'q': back
  Your choice:

UNRESOLVED_TICKETS_PROMPT : |
  Press:
  'd': view ticket in detail
  'r': Resolve tickets
  'n': next page
  'q': back
  Your Choice:

RESOLVED_TICKETS_PROMPT : |
  Press:
  'd': view ticket in detail
  'c': close ticket
  'n': next page
  'q': back
  Your choice: 

CLOSED_TICKETS_PROMPT : |
  Press:
  'd': view ticket in detail
  'n': next page
  'q': back
  Your choice: 

LINE_BREAK : "----------------------------------------"

UNRESOLVED_TICKET_CONTINUE_PROMPT : "Do you want to see the unresolved tickets again?(y/n): "

RESOLVED_TICKETS_CONTINUE_PROMPT : "Do you want to see the resolved tickets again?(y/n): "

END_OF_TICKETS : "---------------------------That's all the tickets we have---------------------------"

CLOSE_TICKET_PROMPT : "Enter the ticket id of the ticket you want to close: "

EMPTY_RESOLVED_TICKETS : "There are no resolved tickets currently"

EMPTY_UNRESOLVED_TICKETS : "There are no unresolved tickets currently"

EMPTY_CLOSED_TICKETS : "There are no closed tickets currently"

CLOSED_TICKETS_CONTINUE_PROMPT : "Do you want to see the closed tickets again?(y/n): "

SUCCESS_SENT : "Successfully Sent."


IN_PROGRESS_DETAILS_PROMPT : |
  Press:
  'c': close this ticket,
  'q': go back
  Your choice: 

RAISED_TICKETS_DETAIL_PROMPT : |
  Press:
  'r': resolve this ticket
  'q': go back
  Your choice:

GO_BACK_PROMPT : "Press q to go back: "

IN_PROGRESS : "in_progress"

CLOSED : 'closed'

RAISED: 'raised'

INVALID_T_ID: "Enter valid ticket id or press q to go back: "