from os import path

import yaml

path_current_directory = path.dirname(__file__)
HELPDESK_TICKET_CONFIG_FILE_PATH = path.join(path_current_directory, 'helpdesk_ticket.yml')


class HelpdeskTicketConfig:
    WELCOME_HELPDESK_SECTION = None
    UNRESOLVED_TICKETS_WELCOME = None
    CLOSE_TICKET_WELCOME = None
    TICKET_IN_DETAIL_WELCOME = None
    PLEASE_ENTER_VALID_INPUT = None
    RESOLVED_TICKET_WELCOME = None
    RESOLVE_TICKET_PROMPT = None
    CLOSED_TICKETS_WELCOME = None
    HELPDESK_TICKET_PROMPT = None
    UNRESOLVED_TICKETS_PROMPT = None
    RESOLVED_TICKETS_PROMPT = None
    CLOSED_TICKETS_PROMPT = None
    LINE_BREAK = None
    UNRESOLVED_TICKET_CONTINUE_PROMPT = None
    RESOLVED_TICKETS_CONTINUE_PROMPT = None
    END_OF_TICKETS = None
    CLOSE_TICKET_PROMPT = None
    EMPTY_RESOLVED_TICKETS = None
    EMPTY_UNRESOLVED_TICKETS = None
    EMPTY_CLOSED_TICKETS = None
    CLOSED_TICKETS_CONTINUE_PROMPT = None
    SUCCESS_SENT = None
    IN_PROGRESS_DETAILS_PROMPT = None
    RAISED_TICKETS_DETAIL_PROMPT = None
    GO_BACK_PROMPT = None
    IN_PROGRESS = None
    CLOSED = None
    RAISED = None
    INVALID_T_ID = None

    @classmethod
    def load(cls):
        with open(HELPDESK_TICKET_CONFIG_FILE_PATH, 'r') as file:
            data = yaml.safe_load(file)
            cls.WELCOME_HELPDESK_SECTION = data['WELCOME_HELPDESK_SECTION']
            cls.UNRESOLVED_TICKETS_WELCOME = data['UNRESOLVED_TICKETS_WELCOME']
            cls.CLOSE_TICKET_WELCOME = data['CLOSE_TICKET_WELCOME']
            cls.TICKET_IN_DETAIL_WELCOME = data['TICKET_IN_DETAIL_WELCOME']
            cls.PLEASE_ENTER_VALID_INPUT = data['PLEASE_ENTER_VALID_INPUT']
            cls.RESOLVED_TICKET_WELCOME = data['RESOLVED_TICKET_WELCOME']
            cls.RESOLVE_TICKET_PROMPT = data['RESOLVE_TICKET_PROMPT']
            cls.CLOSED_TICKETS_WELCOME = data['CLOSED_TICKETS_WELCOME']
            cls.HELPDESK_TICKET_PROMPT = data['HELPDESK_TICKET_PROMPT']
            cls.UNRESOLVED_TICKETS_PROMPT = data['UNRESOLVED_TICKETS_PROMPT']
            cls.RESOLVED_TICKETS_PROMPT = data['RESOLVED_TICKETS_PROMPT']
            cls.CLOSED_TICKETS_PROMPT = data['CLOSED_TICKETS_PROMPT']
            cls.LINE_BREAK = data['LINE_BREAK']
            cls.UNRESOLVED_TICKET_CONTINUE_PROMPT = data['UNRESOLVED_TICKET_CONTINUE_PROMPT']
            cls.RESOLVED_TICKETS_CONTINUE_PROMPT = data['RESOLVED_TICKETS_CONTINUE_PROMPT']
            cls.END_OF_TICKETS = data['END_OF_TICKETS']
            cls.CLOSE_TICKET_PROMPT = data['CLOSE_TICKET_PROMPT']
            cls.EMPTY_RESOLVED_TICKETS = data['EMPTY_RESOLVED_TICKETS']
            cls.EMPTY_UNRESOLVED_TICKETS = data['EMPTY_UNRESOLVED_TICKETS']
            cls.EMPTY_CLOSED_TICKETS = data['EMPTY_CLOSED_TICKETS']
            cls.CLOSED_TICKETS_CONTINUE_PROMPT = data['CLOSED_TICKETS_CONTINUE_PROMPT']
            cls.SUCCESS_SENT = data['SUCCESS_SENT']
            cls.IN_PROGRESS_DETAILS_PROMPT = data['IN_PROGRESS_DETAILS_PROMPT']
            cls.RAISED_TICKETS_DETAIL_PROMPT = data['RAISED_TICKETS_DETAIL_PROMPT']
            cls.GO_BACK_PROMPT = data['GO_BACK_PROMPT']
            cls.IN_PROGRESS = data['IN_PROGRESS']
            cls.RAISED = data['RAISED']
            cls.CLOSED = data['CLOSED']
            cls.INVALID_T_ID = data['INVALID_T_ID']
