DB_FILE_PATH : 'DBUtils\data\csm.db'

INVALID_USERNAME_OR_PASSWORD : 'Invalid Username or password'
INVALID_USERNAME_LOG : 'Invalid Username detected'
INVALID_PASSWORD_LOG : 'Invalid password detected'

ALREADY_EXISTS_EXCEPTION : 'Email already exists, please try a different email'
INVALID_CUST_ID : 'Invalid CustomerID Provided'
INVALID_DEPT_ID : "Invalid department id encountered"
INVALID_EMP_ID : "Invalid employee id encountered"

THERE_WAS_SOME_PROBLEM : "There was some problem."
WE_WILL_GET_BACK : "We will get back to you soon."

IN_PROGRESS : "in_progress"
RAISED : "raised"
CLOSED : "closed"
