CREATE_TABLE_CUST_AUTH : ''
CREATE_TABLE_CUST_DETAILS :
CREATE_TABLE_EMP :
CREATE_TABLE_EMP_DETAILS :
CREATE_TABLE_DEPT_DETAILS :




FIND_USER_QUERY : 'SELECT * FROM {} WHERE email = %(email)s'
FIND_DEPT_BY_DEPTID : 'SELECT dept_name from dept WHERE dept_id=%(dept_id)s'
INSERT_INTO_CUSTOMER_AUTH_TABLE : 'INSERT INTO cust_auth VALUES(%s, %s, %s)'
GET_CUST_DETAILS_BY_ID : 'SELECT * FROM cust_details WHERE c_id = %(c_id)s'
INSERT_INTO_CUST_DETAILS : 'INSERT INTO cust_details VALUES(%s, %s, %s, %s)'


GET_EMPLOYEE_DETAILS_BY_ID : "SELECT * FROM emp_details WHERE e_id = %(e_id)"
DEPT_TABLE_MAPPING_QUERY : "SELECT * FROM dept_details"
GET_DEPT_DETAILS_BY_ID : "SELECT * FROM dept_details WHERE dept_id = %(dept_id)s"
GET_EMPLOYEE_ROLE : "SELECT * FROM emp_auth WHERE e_id = %(e_id)s"



# feedback
CREATE_TABLE_FEEDBACK : 'CREATE TABLE IF NOT EXISTS feedback(f_id TEXT PRIMARY KEY, stars INTEGER, description TEXT, t_id TEXT UNIQUE, FOREIGN KEY(t_id) REFERENCES tickets(t_id))'
GET_FEEDBACK_BY_TID : "SELECT * FROM feedback WHERE t_id=%(t_id)s"
INSERT_INTO_FEEDBACK : 'INSERT INTO feedback VALUES(%s, %s, %s, %s)'
GET_ALL_FEEDBACK : 'SELECT * FROM feedback'

# operations on ticket
CREATE_TABLE_TICKETS:
INSERT_INTO_TICKETS_TABLE : "INSERT INTO tickets(t_id, d_id, c_id, title, desc, status, created_on) VALUES(%s, %s, %s, %s, %s, %s, %s)"
IS_TICKET_CLOSED : 'SELECT * FROM tickets WHERE t_id=%(t_id)s AND status=%(status)s'
UPDATE_TICKET_STATUS : "UPDATE tickets SET status=%(status)s WHERE t_id = %(t_id)s"
VIEW_TICKETS : "SELECT * FROM tickets WHERE c_id=%(c_id)s AND status =%(status)s "
VIEW_TICKETS_BY_STATUS : "SELECT * FROM tickets WHERE status=%(status)s AND d_id=%(d_id)s"
VIEW_ALL_TICKETS : "SELECT * FROM tickets ORDER BY created_on DESC"
ASSIGN_REPR : "UPDATE tickets SET repr_id=%(repr_id)s WHERE t_id=%(t_id)s"


# Message from helpdesk
CREATE_TABLE_MESSAGE_FROM_HELPDESK :
UPDATE_MESSAGE_FROM_HELPDESK : "INSERT INTO message_from_helpdesk VALUES(%s, %s, %s, %s)"
GET_MESSAGE_FROM_HELPDESK : "SELECT * FROM message_from_helpdesk WHERE t_id=%(t_id)s"

# message from manager
CREATE_TABLE_MESSAGE_FROM_MANAGER :
UPDATE_MESSAGE_FROM_MANAGER : "INSERT INTO message_from_manager VALUES(%s, %s, %s, %s)"
GET_MESSAGE_FROM_MANAGER : "SELECT * FROM message_from_manager WHERE t_id=%(t_id)s"

