COMPANY_LOGO : '----------------------------------ABC Customer Service Portal----------------------------------'
CUSTOMER_WELCOME_MENU : "Welcome {} how can we help you?"
CUSTOMER_MENU : |
  Press:
  'r': for raising a ticket or complaint
  'p': for viewing your existing in-progress tickets
  'u': for viewing unresolved/raised tickets
  'c': for viewing requests that have been closed by our representatives
  'q': logout
  Your Choice:
TICKET_RAISED_SUCCESS : "Ticket raised successfully"
HELPDESK_PROMPT: |
  Press: 
  't': tickets section
  'q': logout
  Your Choice:
WELCOME_MESSAGE:  "Hey {}"
MANAGER_PROMPT : |
  Press:
  't': access tickets section
  'f': access feedback section
  'q': logout
  Your Choice:
MANAGER_WELCOME_MESSAGE : "Welcome {}"
FEEDBACK_HANDLER_TITLE : "---------------------------Feedback-------------------------------"
EMPTY_FEEDBACKS : "There are no feedbacks to show"
FEEDBACK_PROMPT : |
  Press:
  'n': next page
  'q': back 
  Your Choice
FEEDBACK_CONTINUE_PROMPT : "Do you want to see the feedbacks again?(y/n): "
END_OF_FEEDBACKS : "That's all the feedback we have"



